/**
 * ShieldPM — CI/CD Integration
 * Generates GitHub Actions workflows, GitLab CI configs, pre-commit hooks,
 * and PR decoration markdown for CI/CD pipeline integration.
 */

import { writeFile, readFile, chmod, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import type { RiskReport, Finding } from '../analyzer/static.js';
import type { LicenseViolation } from '../license/compliance.js';
import type { PolicyEvaluation } from '../policy/engine.js';

// ── Types ────────────────────────────────────────────────────────────────

export type CIProvider = 'github-actions' | 'gitlab-ci' | 'azure-devops';

export interface GateConfig {
  maxRiskScore: number;
  maxCriticalFindings: number;
  maxHighFindings: number;
  blockOnLicenseViolation: boolean;
  blockOnPolicyFailure: boolean;
  blockOnDeniedPackage: boolean;
  failOnNoSBOM: boolean;
}

export interface GateResult {
  passed: boolean;
  checks: GateCheck[];
  summary: string;
  exitCode: number;
}

export interface GateCheck {
  name: string;
  passed: boolean;
  message: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
}

export interface PRComment {
  title: string;
  body: string;
  status: 'success' | 'warning' | 'failure';
}

// ── Default Gate Config ─────────────────────────────────────────────────

export const DEFAULT_GATE: GateConfig = {
  maxRiskScore: 7,
  maxCriticalFindings: 0,
  maxHighFindings: 5,
  blockOnLicenseViolation: true,
  blockOnPolicyFailure: true,
  blockOnDeniedPackage: true,
  failOnNoSBOM: false,
};

// ── GitHub Actions Generator ────────────────────────────────────────────

export function generateGitHubActions(gate: GateConfig = DEFAULT_GATE): string {
  return `# ShieldPM Security Scan — GitHub Actions
# Generated by shieldpm cicd setup --provider github-actions

name: ShieldPM Security Scan

on:
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'package.json'
      - 'package-lock.json'
  push:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  security-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install ShieldPM
        run: npm install -g shieldpm

      - name: Run Security Audit
        run: shieldpm audit --deep --json > shieldpm-report.json
        continue-on-error: true

      - name: Generate SBOM
        run: shieldpm sbom --format cyclonedx --output sbom.json

      - name: License Compliance Check
        run: shieldpm license check

      - name: Policy Gate
        run: |
          shieldpm gate \\
            --max-risk-score ${gate.maxRiskScore} \\
            --max-critical ${gate.maxCriticalFindings} \\
            --max-high ${gate.maxHighFindings} \\
            ${gate.blockOnLicenseViolation ? '--block-license-violations' : ''} \\
            ${gate.blockOnPolicyFailure ? '--block-policy-failures' : ''}

      - name: PR Comment
        if: github.event_name == 'pull_request'
        run: shieldpm pr-comment --format markdown > pr-comment.md

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: shieldpm-report
          path: shieldpm-report.json
`;
}

// ── GitLab CI Generator ─────────────────────────────────────────────────

export function generateGitLabCI(gate: GateConfig = DEFAULT_GATE): string {
  return `# ShieldPM Security Scan — GitLab CI
# Generated by shieldpm cicd setup --provider gitlab-ci

stages:
  - security

shieldpm-scan:
  stage: security
  image: node:20-alpine
  before_script:
    - npm ci
    - npm install -g shieldpm
  script:
    - shieldpm audit --deep --json > shieldpm-report.json
    - shieldpm sbom --format cyclonedx --output sbom.json
    - shieldpm license check
    - >
      shieldpm gate
      --max-risk-score ${gate.maxRiskScore}
      --max-critical ${gate.maxCriticalFindings}
      --max-high ${gate.maxHighFindings}
      ${gate.blockOnLicenseViolation ? '--block-license-violations' : ''}
      ${gate.blockOnPolicyFailure ? '--block-policy-failures' : ''}
  artifacts:
    paths:
      - sbom.json
      - shieldpm-report.json
    when: always
    expire_in: 30 days
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'
`;
}

// ── Azure DevOps Generator ──────────────────────────────────────────────

export function generateAzureDevOps(gate: GateConfig = DEFAULT_GATE): string {
  return `# ShieldPM Security Scan — Azure DevOps
# Generated by shieldpm cicd setup --provider azure-devops

trigger:
  branches:
    include: [main, master]
  paths:
    include: [package.json, package-lock.json]

pr:
  branches:
    include: [main, master]

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Setup Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npm install -g shieldpm
    displayName: 'Install ShieldPM'

  - script: shieldpm audit --deep --json > shieldpm-report.json
    displayName: 'Security Audit'
    continueOnError: true

  - script: shieldpm sbom --format cyclonedx --output sbom.json
    displayName: 'Generate SBOM'

  - script: shieldpm license check
    displayName: 'License Check'

  - script: >
      shieldpm gate
      --max-risk-score ${gate.maxRiskScore}
      --max-critical ${gate.maxCriticalFindings}
      --max-high ${gate.maxHighFindings}
    displayName: 'Policy Gate'

  - publish: sbom.json
    artifact: sbom
    displayName: 'Publish SBOM'
`;
}

// ── Pre-commit Hook ─────────────────────────────────────────────────────

const PRECOMMIT_HOOK = `#!/bin/sh
# ShieldPM pre-commit hook
# Scans package.json changes for new dependencies before commit

set -e

# Check if package.json was modified
if git diff --cached --name-only | grep -q "package.json"; then
  echo "\\033[36m[shieldpm]\\033[0m Package.json changed — running security scan..."

  # Check for new dependencies
  CHANGED=$(git diff --cached package.json)

  if echo "$CHANGED" | grep -q '"dependencies"\\|"devDependencies"'; then
    # Run quick audit on staged changes
    if command -v shieldpm >/dev/null 2>&1; then
      shieldpm audit 2>&1 || {
        echo "\\033[31m[shieldpm]\\033[0m Security scan found issues. Review above."
        echo "\\033[33m[shieldpm]\\033[0m To bypass: git commit --no-verify"
        exit 1
      }

      # Run policy gate if policy exists
      if [ -f "shieldpm-policy.json" ]; then
        shieldpm gate 2>&1 || {
          echo "\\033[31m[shieldpm]\\033[0m Policy gate failed."
          exit 1
        }
      fi

      echo "\\033[32m[shieldpm]\\033[0m Security scan passed."
    else
      echo "\\033[33m[shieldpm]\\033[0m shieldpm not installed. Skipping scan."
      echo "\\033[33m[shieldpm]\\033[0m Install: npm install -g shieldpm"
    fi
  fi
fi
`;

export async function installPreCommitHook(projectDir: string): Promise<string> {
  const hooksDir = join(projectDir, '.git', 'hooks');
  const hookPath = join(hooksDir, 'pre-commit');

  if (!existsSync(join(projectDir, '.git'))) {
    throw new Error('Not a git repository. Run git init first.');
  }

  await mkdir(hooksDir, { recursive: true });

  // Check for existing hook
  if (existsSync(hookPath)) {
    const existing = await readFile(hookPath, 'utf-8');
    if (existing.includes('shieldpm')) {
      return hookPath; // Already installed
    }
    // Append to existing hook
    await writeFile(hookPath, existing + '\n\n' + PRECOMMIT_HOOK, 'utf-8');
  } else {
    await writeFile(hookPath, PRECOMMIT_HOOK, 'utf-8');
  }

  await chmod(hookPath, 0o755);
  return hookPath;
}

// ── PR Comment Generator ────────────────────────────────────────────────

export function generatePRComment(
  reports: Map<string, RiskReport>,
  licenseViolations: LicenseViolation[] = [],
  policyResults: PolicyEvaluation[] = [],
  gateResult?: GateResult
): PRComment {
  const totalPkgs = reports.size;
  const highRisk = [...reports.values()].filter((r) => r.score >= 7).length;
  const medRisk = [...reports.values()].filter((r) => r.score >= 4 && r.score < 7).length;
  const totalFindings = [...reports.values()].reduce((sum, r) => sum + r.findings.length, 0);
  const avgScore = totalPkgs > 0
    ? ([...reports.values()].reduce((sum, r) => sum + r.score, 0) / totalPkgs).toFixed(1)
    : '0.0';

  const status: PRComment['status'] = highRisk > 0 || licenseViolations.length > 0
    ? 'failure'
    : medRisk > 0
      ? 'warning'
      : 'success';

  const statusEmoji = status === 'success' ? '&#9989;' : status === 'warning' ? '&#9888;&#65039;' : '&#10060;';
  const statusText = status === 'success' ? 'Passed' : status === 'warning' ? 'Warnings' : 'Failed';

  let body = `## ${statusEmoji} ShieldPM Security Scan — ${statusText}\n\n`;

  // Summary table
  body += `| Metric | Value |\n|--------|-------|\n`;
  body += `| Packages Scanned | ${totalPkgs} |\n`;
  body += `| Average Risk Score | ${avgScore}/10 |\n`;
  body += `| High Risk Packages | ${highRisk} |\n`;
  body += `| Total Findings | ${totalFindings} |\n`;
  body += `| License Violations | ${licenseViolations.length} |\n`;
  body += `| Policy Failures | ${policyResults.filter((p) => p.blocked).length} |\n\n`;

  // High-risk packages
  if (highRisk > 0) {
    body += `### High-Risk Packages\n\n`;
    body += `| Package | Score | Findings |\n|---------|-------|----------|\n`;
    for (const [name, report] of reports) {
      if (report.score >= 7) {
        body += `| \`${name}\` | **${report.score}/10** | ${report.findings.length} |\n`;
      }
    }
    body += '\n';
  }

  // License violations
  if (licenseViolations.length > 0) {
    body += `### License Violations\n\n`;
    body += `| Package | License | Issue |\n|---------|---------|-------|\n`;
    for (const v of licenseViolations.slice(0, 10)) {
      body += `| \`${v.packageName}\` | ${v.license} | ${v.message} |\n`;
    }
    if (licenseViolations.length > 10) {
      body += `\n*...and ${licenseViolations.length - 10} more violations*\n`;
    }
    body += '\n';
  }

  // Gate result
  if (gateResult) {
    body += `### Gate Result: ${gateResult.passed ? 'PASSED' : 'FAILED'}\n\n`;
    for (const check of gateResult.checks) {
      const icon = check.passed ? '&#9989;' : '&#10060;';
      body += `- ${icon} ${check.name}: ${check.message}\n`;
    }
    body += '\n';
  }

  body += `---\n*Generated by [ShieldPM](https://github.com/nrupaks/shieldpm) — Runtime-aware package firewall for Node.js*\n`;

  return {
    title: `ShieldPM: ${statusText} (${totalPkgs} packages, ${highRisk} high-risk)`,
    body,
    status,
  };
}

// ── Break-the-Build Gate ────────────────────────────────────────────────

export function evaluateGate(
  reports: Map<string, RiskReport>,
  config: GateConfig = DEFAULT_GATE,
  licenseViolations: LicenseViolation[] = [],
  policyBlocked: boolean = false,
  deniedPackages: string[] = []
): GateResult {
  const checks: GateCheck[] = [];
  let exitCode = 0;

  // Check max risk score
  let maxScore = 0;
  let maxPkg = '';
  for (const [name, report] of reports) {
    if (report.score > maxScore) {
      maxScore = report.score;
      maxPkg = name;
    }
  }
  const riskPassed = maxScore <= config.maxRiskScore;
  checks.push({
    name: 'Max Risk Score',
    passed: riskPassed,
    message: riskPassed
      ? `Highest risk: ${maxScore.toFixed(1)}/10 (threshold: ${config.maxRiskScore})`
      : `"${maxPkg}" has risk score ${maxScore.toFixed(1)}/10 (max allowed: ${config.maxRiskScore})`,
    severity: 'critical',
  });
  if (!riskPassed) exitCode = 1;

  // Check critical findings
  let totalCritical = 0;
  for (const report of reports.values()) {
    totalCritical += report.findings.filter((f) => f.severity === 'critical').length;
  }
  const critPassed = totalCritical <= config.maxCriticalFindings;
  checks.push({
    name: 'Critical Findings',
    passed: critPassed,
    message: critPassed
      ? `${totalCritical} critical findings (max: ${config.maxCriticalFindings})`
      : `${totalCritical} critical findings exceed limit of ${config.maxCriticalFindings}`,
    severity: 'critical',
  });
  if (!critPassed) exitCode = 1;

  // Check high findings
  let totalHigh = 0;
  for (const report of reports.values()) {
    totalHigh += report.findings.filter((f) => f.severity === 'high').length;
  }
  const highPassed = totalHigh <= config.maxHighFindings;
  checks.push({
    name: 'High Findings',
    passed: highPassed,
    message: highPassed
      ? `${totalHigh} high findings (max: ${config.maxHighFindings})`
      : `${totalHigh} high findings exceed limit of ${config.maxHighFindings}`,
    severity: 'high',
  });
  if (!highPassed) exitCode = 1;

  // License violations
  if (config.blockOnLicenseViolation) {
    const licPassed = licenseViolations.length === 0;
    checks.push({
      name: 'License Compliance',
      passed: licPassed,
      message: licPassed ? 'No license violations' : `${licenseViolations.length} license violation(s)`,
      severity: 'high',
    });
    if (!licPassed) exitCode = 1;
  }

  // Policy failures
  if (config.blockOnPolicyFailure) {
    checks.push({
      name: 'Policy Compliance',
      passed: !policyBlocked,
      message: policyBlocked ? 'Policy evaluation blocked one or more packages' : 'All packages pass policy',
      severity: 'critical',
    });
    if (policyBlocked) exitCode = 1;
  }

  // Denied packages
  if (config.blockOnDeniedPackage && deniedPackages.length > 0) {
    checks.push({
      name: 'Denied Packages',
      passed: false,
      message: `${deniedPackages.length} denied package(s): ${deniedPackages.join(', ')}`,
      severity: 'critical',
    });
    exitCode = 1;
  }

  const passed = exitCode === 0;
  const failedCount = checks.filter((c) => !c.passed).length;
  const summary = passed
    ? `All ${checks.length} gate checks passed`
    : `${failedCount} of ${checks.length} gate checks failed`;

  return { passed, checks, summary, exitCode };
}

// ── CI/CD File Writer ───────────────────────────────────────────────────

export async function setupCICD(
  projectDir: string,
  provider: CIProvider,
  gate: GateConfig = DEFAULT_GATE
): Promise<string> {
  switch (provider) {
    case 'github-actions': {
      const dir = join(projectDir, '.github', 'workflows');
      await mkdir(dir, { recursive: true });
      const path = join(dir, 'shieldpm.yml');
      await writeFile(path, generateGitHubActions(gate), 'utf-8');
      return path;
    }
    case 'gitlab-ci': {
      const path = join(projectDir, '.gitlab-ci-shieldpm.yml');
      await writeFile(path, generateGitLabCI(gate), 'utf-8');
      return path;
    }
    case 'azure-devops': {
      const path = join(projectDir, 'azure-pipelines-shieldpm.yml');
      await writeFile(path, generateAzureDevOps(gate), 'utf-8');
      return path;
    }
    default:
      throw new Error(`Unknown CI provider: ${provider}`);
  }
}
